version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_tmp:/tmp/localstack
      - ./env/aws:/docker-entrypoint-initaws.d
      - .:/usr/src

volumes:
  localstack_tmp:
    name: localstack_tmp